name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  pull_request: {}
  push:
    tags: ["v*.*.*"]

jobs:
  publish:
    if: github.event_name == 'push'
    uses: BitskiCo/bitski-internal-sdk/.github/workflows/docker.yaml@v1
    with:
      build_args: BASE_IMAGE=cockroachdb/cockroach:${{ github.ref_name }}
      push: true
      startup_test: true
      startup_image_env_name: COCKROACH_IMAGE
