name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  pull_request: {}
  push:
    tags: ["latest", "v*.*.*"]
  schedule:
    - cron: "24 0 * * 0"

jobs:
  publish:
    if: >
      github.event_name != 'workflow_run' ||
      github.event.workflow_run.conclusion == 'success'
    uses: BitskiCo/bitski-internal-sdk/.github/workflows/docker.yaml@v1
    with:
      build_args: BASE_IMAGE=cockroachdb/cockroach:${{ github.ref_name }}
      push: ${{ github.event_name != 'pull_request' }}
      startup_test: true
      startup_image_env_name: COCKROACH_IMAGE
